2024-02-29 16:44:37,370:ERROR:Request-ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) ID283180018
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 323, in search_query
    r = s.get(url, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-29 16:44:37,417:ERROR:'str' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'content'
2024-02-29 16:44:39,494:ERROR:Request-Exception: ('Connection broken: IncompleteRead(7851 bytes read, 341 more expected)', IncompleteRead(7851 bytes read, 341 more expected)) RP904064675
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\response.py", line 710, in _error_catcher
    yield
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\response.py", line 1080, in read_chunked
    chunk = self._handle_chunk(amt)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\response.py", line 1031, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)  # type: ignore[union-attr]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(7851 bytes read, 341 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\response.py", line 937, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\response.py", line 1065, in read_chunked
    with self._error_catcher():
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(7851 bytes read, 341 more expected)', IncompleteRead(7851 bytes read, 341 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 323, in search_query
    r = s.get(url, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(7851 bytes read, 341 more expected)', IncompleteRead(7851 bytes read, 341 more expected))
2024-02-29 16:44:39,969:ERROR:'str' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'content'
2024-02-29 16:44:40,763:ERROR:Request-ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) ID308434985
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 323, in search_query
    r = s.get(url, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-29 16:44:40,768:ERROR:'str' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'content'
2024-02-29 16:44:42,278:ERROR:Request-ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) RP772518064
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 323, in search_query
    r = s.get(url, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sandeep Kumar\miniconda3\envs\ticketing\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-29 16:44:42,283:ERROR:'str' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'content'
2024-02-29 16:45:50,112:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:50,135:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:50,205:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:50,211:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:50,803:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:50,811:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:50,811:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:50,812:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:51,039:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:51,039:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 244, in get_ticket_html_content
    soup = BeautifulSoup(ticketContent.content, 'html5lib')
                         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:51,365:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:51,367:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:51,368:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:51,368:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:51,538:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:51,538:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:51,874:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:51,882:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:51,930:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:51,962:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:52,155:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:52,195:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:52,859:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:52,910:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:53,010:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:53,020:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:53,049:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:53,096:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:53,729:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:53,730:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:53,923:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:53,931:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:53,931:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:53,932:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,079:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,087:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,088:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 244, in get_ticket_html_content
    soup = BeautifulSoup(ticketContent.content, 'html5lib')
                         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,088:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 244, in get_ticket_html_content
    soup = BeautifulSoup(ticketContent.content, 'html5lib')
                         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,218:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,218:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,438:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,442:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,442:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,443:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,582:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,588:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,589:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,589:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,709:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,709:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,944:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,952:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:54,953:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:54,954:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,103:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,110:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,110:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,110:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,199:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,200:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,450:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,455:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,456:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,457:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,605:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,612:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,612:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,612:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,708:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,709:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,958:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,968:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:55,969:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:55,970:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,103:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,113:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,113:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,114:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,275:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,276:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,531:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,539:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,539:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,539:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,607:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,615:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,615:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,615:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:56,766:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:56,767:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,034:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,040:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,041:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,041:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,111:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,113:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,113:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,114:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,252:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,253:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,561:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,569:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,570:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,569:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,615:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,616:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,624:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,625:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:57,745:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:57,746:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,062:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,069:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,070:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,070:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,114:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,115:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,126:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,126:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,306:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,306:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,563:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,563:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,574:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,575:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,613:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,622:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,622:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,623:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:58,812:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:58,815:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:59,064:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:59,072:ERROR:Search_Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\searchTicket.py", line 329, in search_query
    _dict["sessionError"].emit(True)
    ~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-02-29 16:45:59,073:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
2024-02-29 16:45:59,073:ERROR:'TypeError' object has no attribute 'content'
Traceback (most recent call last):
  File "C:\Users\Sandeep Kumar\Desktop\search-ticketing\escalation_tracker.py", line 240, in get_ticket_html_content
    searchSoup = BeautifulSoup(ticketSearch.content, 'html5lib')
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute 'content'
